### ISSUE TITLE
Preview window does not highlight all matches

### ISSUE THREAD

**Issue by diego898** [bellecp/fast-p#10]
On OSX the match isn't highlighted in my preview window for some returned items, but it is in others. (Im not sure if this is an issue here, or with fzf). For example, if I search "test" the first few results might hate test@email.com directly in the preview window, it just isnt highlighted. If I keep scrolling down other results show them and are indeed highlighted.

**Comment by bellecp** [comment]
I believe this is an issue with fzf. It is because the preview window is not updated until the previewed result is changed. If you query "t", it may find the result you are looking before before typing the full query "test". But when you are done typing "test", the previewed result has not been updated, and it still highlights with "t". This is also the case if you do not type anything, provided that the first result contains the query that will be typed.

You may fix the highlighting by selecting the next result (down-arrow) and back to the first result (up-arrow).
