### ISSUE TITLE
pdf-to-text only extracts first tiny part of document

### ISSUE THREAD

**Issue by ruthwild** [bellecp/fast-p#22]
hi^^ i tried today to use fast-p to make some math papers more searchable, but it just stops after a tiny fraction of the document.
using pdftotext on the same pdf works fine, then the whole thing is turned into a txt.
i've attached the cache-file when using fast-p in a folder that contains just a trial file (i had to change the ending bc github didn't let me upload a .db file but the content is the same...)
[fast-p_cached_pdftotext_output.txt](https://github.com/bellecp/fast-p/files/8918823/fast-p_cached_pdftotext_output.txt)

**Comment by bellecp** [comment]
Only the first two pages are extracted because this is typically where to find the author, title and abstract. The goal is only to find the pdf of the paper you are looking for, not to find certain keywrods in the whole document.

``fzf`` which processes the extracted text as a single line would not be well-suited to process dozens of pages of extracted text. If you are interested in searching in the whole pdf beyond the first 2 pages, I suggest https://github.com/phiresky/ripgrep-all

**Comment by ruthwild** [comment]
my bad. sorry for rasing the (non-)issue!

**Comment by SuperCowProducts** [comment]
> Only the first two pages are extracted because this is typically where to find the author, title and abstract. The goal is only to find the pdf of the paper you are looking for, not to find certain keywrods in the whole document.
> 
> `fzf` which processes the extracted text as a single line would not be well-suited to process dozens of pages of extracted text. If you are interested in searching in the whole pdf beyond the first 2 pages, I suggest https://github.com/phiresky/ripgrep-all

That's a pity, `rga` piped into `fzf` is ok but often the most useful 'semantic' matches happen at paragraph-level!
